foodlovers/urls.py
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import CreateView
from photologue.models import Photo,Gallery
from photologue.views import PhotoListView, PhotoDetailView, GalleryListView, \
    GalleryDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, GalleryArchiveIndexView, GalleryYearArchiveView, \
    GalleryDateDetailView, GalleryDayArchiveView, GalleryMonthArchiveView

    
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'foodlovers.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

url(r'^photo/comments/', include('django_comments.urls')),	
url(r'^photologue/photo/add/$', CreateView.as_view(model=Photo, success_url='/photologue/photolist',fields=('image','title','slug',)),
        name='add-photo'),
url(r'^photologue/gallery/add/$', CreateView.as_view(model=Gallery, success_url='/photologue/gallery',fields=('photos','title','slug','description',)),
        name='add-gallery'),		
url(r'^login/$', 'appusers.views.mylogin', name='login'),
   url(r'^logout/$', 'appusers.views.mylogout', name='logout'),
                       
        url(r'^friends/', include('friends.urls')),               
                       
                       
     url(r'^show_feed/$', 'appusers.views.show_feed', name='show_feed'),                   
                       
    url(r'^home/$', 'photobucket.views.home', name='home'),
        url(r'^feed/$', 'photobucket.views.home', name='home'),
                   
url(r'^home/users/(?P<user_id>[\d]+)/$','appusers.views.show_user_id',name='show_user_id'),
                       #rl(r'^login/$', 'appusers.views.register', name='register'),
	 url(r'^searchuser/$', 'appusers.views.autocomplete', name='autocomplete'),
	 url(r'^tagsearch/$', 'appusers.views.tagsearch', name='search'),
    url(r'^userphoto/tagsearch/$', 'appusers.views.tagsearch', name='search'),
                   
	 url(r'^addprofilepic/$', 'appusers.views.addprofilepic', name='addprofilepic'), 
	 url(r'^delprofilepic/$', 'appusers.views.delprofilepic', name='delprofilepic'), 
                       
	  url(r'^addphoto/$', 'photobucket.views.addphoto', name='addphoto'),
	  url(r'^addrecipe/$', 'photobucket.views.addrecipe', name='addrecipe'),
	  url(r'^recipes/$', 'photobucket.views.recipelist', name='recipelist'),
	  url(r'^myrecipes/$', 'photobucket.views.user_recipe', name='user_recipe'),
                       
     url(r"^notifications/", include("pinax.notifications.urls")),                  
      url(r'^friend_feed/$', 'appusers.views.friend_feed', name='friend_feed'),                 
	  url(r'^deletephoto/$', 'photobucket.views.delete_photo', name='delete_photo'),
	  url(r'^deleterecipe/$', 'photobucket.views.delete_recipe', name='delete_recipe'),
                       
      url(r'^reportphoto/$', 'photobucket.views.reportphoto', name='reportphoto'),                  
      url(r'^reportrecipe/$', 'photobucket.views.reportrecipe', name='reportrecipe'),                  
    url(r'^addcomment/$', 'photobucket.views.addcomment', name='addcomment'),
	  url(r'^addcommentrecipe/$', 'photobucket.views.addcomment_recipe', name='addcomment_recipe'),

    url(r'^thanku/$', 'photobucket.views.thanks', name='thanks'),
	url(r'^userphoto/$', 'photobucket.views.photosort', name='photosort'),
	url(r'^profile/$', 'appusers.views.profile', name='profile'),
	url(r'^vote/$', 'photobucket.views.vote', name='vote'),
    url(r'^voterecipe/$', 'photobucket.views.voterecipe', name='voterecipe'),
                   
	url(r'^pin_photo/$', 'photobucket.views.pin_photo', name='pin_photo'),
	url(r'^pin_recipe/$', 'photobucket.views.pin_recipe', name='pin_recipe'),

    url(r'^pinned/$', 'photobucket.views.pinlist', name='pinlist'),
              
                       
    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),                   
                       
                       
    url(r'^admin/', include(admin.site.urls)),
	url(r'^sign_up/', ('appusers.views.register_user')),
    url(r'^register_success/', ('appusers.views.register_success')),
    url(r'^accounts/confirm/(?P<activation_key>\w+)/', ('appusers.views.register_confirm')),
	url(r'^photologue/', include('photologue.urls')),
		url(r'^photologue/', include('photologue.urls', namespace='photologue')),	
	url(r'^addinfo/$', 'appusers.views.addinfo', name='addinfo'),
	url(r'^profile/edituserinfo/$', 'appusers.views.edituserinfo', name='edituserinfo'),
                       
	url(r'^facebook/$', include('django_facebook.urls')),
url(r'^accounts/', include('django_facebook.auth_urls')),
url('', include('social.apps.django_app.urls', namespace='social')),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

appusers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils import timezone
# Create your models here.
class MyUser(AbstractUser):
    GENDER_CHOICES = (('M', 'Male'),('F', 'Female'),)
    profile_pic = models.ImageField(upload_to = 'profile_pics/', blank = True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=GENDER_CHOICES[0][0])
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(max_length=15,validators=[phone_regex], blank=True) # validators should be a list
    dob = models.DateField(blank=True, null=True)
    street_address = models.CharField(max_length = 100, null=True, blank=True)
    city = models.CharField( blank=True, null=True, max_length=255)
    pincode = models.CharField(max_length=8, default="0000000")
    following = models.ManyToManyField("self", symmetrical = False, related_name = "followers")
    email_id=models.EmailField(max_length=255)
    #pinned_photo=models.ForeignKey(Pinned_Photo,null=True,blank=True)
    #pinned_recipe=models.ForeignKey(Pinned_Recipe,null=True,blank=True)

    
    def image_tag(self):
        if self.profile_pic:
            return '<img height="40px" width="40px" src="/media/%s">' % self.profile_pic
        else:
            return ''
        image_tag.short_description = 'Image'
        image_tag.allow_tags = 'True'
    
    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "username__icontains", "first_name__icontains", "last_name__icontains")

class UserProfile(models.Model):
    user = models.OneToOneField(MyUser)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=timezone.now())
      
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural=u'User profiles'
		
"""African=0
American=1
Argentinian=2
Brazilian=3
Cajun=4
Caribbean=5
Chinese=6
Cuban=7
EastIndian=8
Egyptian=9
Ethiopian=10
French=11
Filipino=12
German=13
Greek=14
Hawaiian=15
Indonesian=16
Italian=17
Iranian=18
Irish=19
Japanese=20
Korean=21
Lebanese=22   
Mediterranean=23
Mexican=24
Mongolian=25
Mughlai=26
NorthIndian=27
Polish=28
Portuguese=29
Scottish=30
SeaFood=31
Spanish=32
SouthIndian=33
Swedish=34
Thai=35
Turkish=36
Vietnamese=37
WestIndian=38
    """
CUISINES_CHOICES = (
       ("African","African"),("American","American"),("Argentinian","Argentinian"),("Brazilian","Brazilian"),("Cajun","Cajun"),("Caribbean","Caribbean"),("Chinese","Chinese"),("Cuban","Cuban"),("EastIndian","EastIndian"),("Egyptian","Egyptian"),("Ethiopian","Ethiopian"),("French","French"),("Filipino","Filipino"),("German","German"),("Greek","Greek"),("Hawaiian","Hawaiian"),("Indonesian","Indonesian"),("Italian","Italian"),("Iranian","Iranian"),("Irish","Irish"),("Japanese","Japanese"),("Korean","Korean"),("Lebanese","Lebanese"),("Mediterranean","Mediterranean"),("Mexican","Mexican"),("Mongolian","Mongolian"),("Mughlai","Mughlai"),("NorthIndian","NorthIndian"),("Polish","Polish"),("Portuguese","Portuguese"),("Scottish","Scottish"),("SeaFood","SeaFood"),("Spanish","Spanish"),("SouthIndian","SouthIndian"),("Swedish","Swedish"),("Thai","Thai"),("Turkish","Turkish"),("Vietnamese","Vietnamese"),("WestIndian","WestIndian"),
)    
        
class cuisine_choice(models.Model):
    cuisines=models.CharField(choices=CUISINES_CHOICES , max_length=25,default='NorthIndian')
    def __str__(self):
        return self.cuisines
       # choices_dict = dict(CUISINES_CHOICES)
        #return choices_dict[self.cuisines]
    
    
        
class UserInfo(models.Model):
    user=models.OneToOneField(MyUser)
    info=models.CharField(max_length=300 , null=True)
    recommended_dish=models.CharField(max_length=100 ,null=True)
    fav_restro=models.CharField(max_length=100 , null=True)
    disliked_food=models.CharField(max_length=50 ,null=True)
    favourite_cuisine=models.CharField(max_length=30,choices=CUISINES_CHOICES,default='none')
    def __str__(self):
        return self.user.username
	


    
    

class Connection(models.Model):
    user1 = models.ForeignKey(MyUser, limit_choices_to={'is_active': True}, related_name = 'connection_user1')
    user2 = models.ForeignKey(MyUser, limit_choices_to={'is_active': True}, related_name = 'connection_user2')
    
    class Meta:
        unique_together=('user1','user2')
        verbose_name = 'Connection'
        verbose_name_plural = 'Connections'
        
    def __str__(self):
        return self.user2.username	

	
	
	
	

    
		
		

templates/user_profile/base.html
{% load static %}
<!doctype html>
<html>
<head>
   <script  src="{% static "js/jquery-2.1.3.js"%}" type="text/javascript"></script>
    	  <link  type="text/css" href="{% static "css/materialize.min.css"%}" rel="stylesheet"  media="screen,projection">
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
               <script  src="{% static "js/materialize.min.js"%}" type="text/javascript"></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/user_profile/confirm.html
{% extends "base.html" %}


{% block content %}
<h1>Registration Complete</h1>
        <p>You are now registered</p>		
{% endblock %}

templates/user_profile/register.html
{% extends "base.html" %}

{% block content %}
<div class="row" >
       <div class="col m4 offset-m2 ">
<form class="form-signup" action="/sign_up/" method="post">{% csrf_token %}
    <h2>Create your account</h2>
    <div class="row">
<div class="input-field  col s6 ">
        <label>First name</label>
      <input id="id_first_name" maxlength="30" name="first_name" type="text" class="validate">
        </div>
   
<div class="input-field  col s6 ">
        <label>Last name</label>
       <input id="id_last_name" maxlength="30" name="last_name" type="text">
    </div> 
    </div>

   <div class="row">
<div class="input-field  col s12 ">    
        {{ form.email.errors }}            
        <label>E-mail</label>
       <input id="id_email" maxlength="254" name="email" type="email">
    </div>    
    </div>
    <div class="row">
<div class="input-field  col s12 ">
    {{form.errors.values.0}}                
        <label>Username</label>
<input id="id_username" maxlength="30" name="username" type="text">        
        </div>
    </div>
    
<div class="row">
<div class="input-field  col s12 ">      
                    
        <label>phone</label>                   
        <input id="id_phone" maxlength="15" name="phone" type="text">
    </div>
    </div>
    
<div class="row">
<div class="input-field  col s6 ">                    
        <label>dob</label>                    
       <input id="id_dob" name="dob" type="text">
    </div>
   
    
<div class="input-field  col s6"> 
	                
      <select id="id_gender" name="gender">
<option value="M" selected="selected">Male</option>
<option value="F">Female</option>
</select>
     <label for="id_gender">gender</label>
    <script>
$(document).ready(function() {
    $('select').material_select();
  });
       </script>
    </div>
    </div>
<div class="row">
<div class="input-field  col s12 ">        
    {{form.errors.values.1}}            
        <label>Password</label>                   
<input id="id_password1" name="password1" type="password">    
    </div>
    </div>
<div class="row">
<div class="input-field  col s12 ">        
    <label>Password again</label>
<input id="id_password2" name="password2" type="password">    
    </div>
    </div>
    
<i class="btn waves-effect waves-light waves-input-wrapper" style=""><input type="submit" name="submit" class="waves-button-input" value="Create account"></i></form>
</div>
</div>
{% endblock %}

templates/user_profile/register_success.html
{% extends "base.html" %}


{% block body_block %}
<h1>Registration Complete</h1>
        <p>You are now registered</p>
{% endblock %}