foodlovers/urls.py
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import CreateView
from photologue.models import Photo,Gallery
from photologue.views import PhotoListView, PhotoDetailView, GalleryListView, \
    GalleryDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, GalleryArchiveIndexView, GalleryYearArchiveView, \
    GalleryDateDetailView, GalleryDayArchiveView, GalleryMonthArchiveView

    
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'foodlovers.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

url(r'^photo/comments/', include('django_comments.urls')),	
url(r'^photologue/photo/add/$', CreateView.as_view(model=Photo, success_url='/photologue/photolist',fields=('image','title','slug',)),
        name='add-photo'),
url(r'^photologue/gallery/add/$', CreateView.as_view(model=Gallery, success_url='/photologue/gallery',fields=('photos','title','slug','description',)),
        name='add-gallery'),		
url(r'^login/$', 'appusers.views.mylogin', name='login'),
   url(r'^logout/$', 'appusers.views.mylogout', name='logout'),
                       
        url(r'^friends/', include('friends.urls')),               
                       
                       
     url(r'^show_feed/$', 'appusers.views.show_feed', name='show_feed'),                   
                       
    url(r'^home/$', 'photobucket.views.home', name='home'),
        url(r'^feed/$', 'photobucket.views.home', name='home'),
                   
url(r'^home/users/(?P<user_id>[\d]+)/$','appusers.views.show_user_id',name='show_user_id'),
                       #rl(r'^login/$', 'appusers.views.register', name='register'),
	 url(r'^searchuser/$', 'appusers.views.autocomplete', name='autocomplete'),
	 url(r'^tagsearch/$', 'appusers.views.tagsearch', name='search'),
    url(r'^userphoto/tagsearch/$', 'appusers.views.tagsearch', name='search'),
                   
	 url(r'^addprofilepic/$', 'appusers.views.addprofilepic', name='addprofilepic'), 
	 url(r'^delprofilepic/$', 'appusers.views.delprofilepic', name='delprofilepic'), 
                       
	  url(r'^addphoto/$', 'photobucket.views.addphoto', name='addphoto'),
	  url(r'^addrecipe/$', 'photobucket.views.addrecipe', name='addrecipe'),
	  url(r'^recipes/$', 'photobucket.views.recipelist', name='recipelist'),
	  url(r'^myrecipes/$', 'photobucket.views.user_recipe', name='user_recipe'),
                       
     url(r"^notifications/", include("pinax.notifications.urls")),                  
      url(r'^friend_feed/$', 'appusers.views.friend_feed', name='friend_feed'),                 
	  url(r'^deletephoto/$', 'photobucket.views.delete_photo', name='delete_photo'),
	  url(r'^deleterecipe/$', 'photobucket.views.delete_recipe', name='delete_recipe'),
                       
      url(r'^reportphoto/$', 'photobucket.views.reportphoto', name='reportphoto'),                  
      url(r'^reportrecipe/$', 'photobucket.views.reportrecipe', name='reportrecipe'),                  
    url(r'^addcomment/$', 'photobucket.views.addcomment', name='addcomment'),
	  url(r'^addcommentrecipe/$', 'photobucket.views.addcomment_recipe', name='addcomment_recipe'),

    url(r'^thanku/$', 'photobucket.views.thanks', name='thanks'),
	url(r'^userphoto/$', 'photobucket.views.photosort', name='photosort'),
	url(r'^profile/$', 'appusers.views.profile', name='profile'),
	url(r'^vote/$', 'photobucket.views.vote', name='vote'),
    url(r'^voterecipe/$', 'photobucket.views.voterecipe', name='voterecipe'),
                   
	url(r'^pin_photo/$', 'photobucket.views.pin_photo', name='pin_photo'),
	url(r'^pin_recipe/$', 'photobucket.views.pin_recipe', name='pin_recipe'),

    url(r'^pinned/$', 'photobucket.views.pinlist', name='pinlist'),
              
                       
    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),                   
                       
                       
    url(r'^admin/', include(admin.site.urls)),
	url(r'^sign_up/', ('appusers.views.register_user')),
    url(r'^register_success/', ('appusers.views.register_success')),
    url(r'^accounts/confirm/(?P<activation_key>\w+)/', ('appusers.views.register_confirm')),
	url(r'^photologue/', include('photologue.urls')),
		url(r'^photologue/', include('photologue.urls', namespace='photologue')),	
	url(r'^addinfo/$', 'appusers.views.addinfo', name='addinfo'),
	url(r'^profile/edituserinfo/$', 'appusers.views.edituserinfo', name='edituserinfo'),
                       
	url(r'^facebook/$', include('django_facebook.urls')),
url(r'^accounts/', include('django_facebook.auth_urls')),
url('', include('social.apps.django_app.urls', namespace='social')),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

photobucket/models.py
from django.db import models
from appusers.models import MyUser

# Create your models here.
class HashTag(models.Model):
    name = models.CharField(max_length = 100)
    count = models.IntegerField(default = 0)
    def __str__(self):
        return '#' + self.name
    
class Recipe(models.Model):
    cuisine_choices = (
    ("African","African"),("American","American"),("Argentinian","Argentinian"),("Brazilian","Brazilian"),("Cajun","Cajun"),("Caribbean","Caribbean"),("Chinese","Chinese"),("Cuban","Cuban"),("EastIndian","EastIndian"),("Egyptian","Egyptian"),("Ethiopian","Ethiopian"),("French","French"),("Filipino","Filipino"),("German","German"),("Greek","Greek"),("Hawaiian","Hawaiian"),("Indonesian","Indonesian"),("Italian","Italian"),("Iranian","Iranian"),("Irish","Irish"),("Japanese","Japanese"),("Korean","Korean"),("Lebanese","Lebanese"),("Mediterranean","Mediterranean"),("Mexiacan","Mexiacan"),("Mongolian","Mongolian"),("Mughlai","Mughlai"),("NorthIndian","NorthIndian"),("Polish","Polish"),("Portuguese","Portuguese"),("Scottish","Scottish"),("SeaFood","SeaFood"),("Spanish","Spanish"),("SouthIndian","SouthIndian"),("Swedish","Swedish"),("Thai","Thai"),("Turkish","Turkish"),("Vietnamese","Vietnamese"),("WestIndian","WestIndian"),
    
    )
    by=models.ForeignKey(MyUser)
    photo=models.ImageField(upload_to='recipe_images/')
    on=models.DateTimeField(auto_now_add = True)
    cuisine=models.CharField(max_length=30,choices=cuisine_choices,default='none')
    title=models.TextField(max_length=100)
    likers = models.ManyToManyField(MyUser, related_name = 'recipe_liked')
    pinners=models.ManyToManyField(MyUser,related_name='recipe_pinned',blank=True)
    reporters=models.ManyToManyField(MyUser,related_name='recipes_reported',through='Report_Recipe')
    pin_points=models.IntegerField(default=0)
    points=models.IntegerField(default=0)
    ingredients=models.TextField(max_length=1000)
    method=models.TextField(max_length=2000)
    prep_time=models.DurationField(null=True,blank=True)
    cook_time=models.DurationField()

    
    def __str__(self):
        return self.title

    
class Report_Recipe(models.Model):
    by=models.ForeignKey(MyUser,related_name='reported_recipe',on_delete=models.CASCADE)
    on=models.DateTimeField(auto_now_add = True)
    recipe=models.ForeignKey(Recipe,on_delete=models.CASCADE)
    report_reasons = (
        ('This recipe is a spam or a scam', 'This recipe is spam or a scam'),
        ('This recipe puts people at risk', 'This recipe puts people at risk'),
        ("This recipe shouldn't be on foodchaps", "This recipe shouldn't be on foodchaps"),
    )
    reason=models.CharField(max_length=40,choices=report_reasons,default="none")
    def __str__(self):
        return self.reason

   
    
class Photo(models.Model):
    cuisine_choices = (
    ("African","African"),("American","American"),("Argentinian","Argentinian"),("Brazilian","Brazilian"),("Cajun","Cajun"),("Caribbean","Caribbean"),("Chinese","Chinese"),("Cuban","Cuban"),("EastIndian","EastIndian"),("Egyptian","Egyptian"),("Ethiopian","Ethiopian"),("French","French"),("Filipino","Filipino"),("German","German"),("Greek","Greek"),("Hawaiian","Hawaiian"),("Indonesian","Indonesian"),("Italian","Italian"),("Iranian","Iranian"),("Irish","Irish"),("Japanese","Japanese"),("Korean","Korean"),("Lebanese","Lebanese"),("Mediterranean","Mediterranean"),("Mexican","Mexican"),("Mongolian","Mongolian"),("Mughlai","Mughlai"),("NorthIndian","NorthIndian"),("Polish","Polish"),("Portuguese","Portuguese"),("Scottish","Scottish"),("SeaFood","SeaFood"),("Spanish","Spanish"),("SouthIndian","SouthIndian"),("Swedish","Swedish"),("Thai","Thai"),("Turkish","Turkish"),("Vietnamese","Vietnamese"),("WestIndian","WestIndian"),
    
    )
    image = models.ImageField(upload_to = 'uploads/')
    place=models.CharField(max_length = 100,default='none')
    by = models.ForeignKey(MyUser, related_name = 'photos_uploaded')
    on = models.DateTimeField(auto_now_add = True)
    description = models.TextField(max_length = 120, null = True)
    likers = models.ManyToManyField(MyUser, related_name = 'photos_liked')
    reporters=models.ManyToManyField(MyUser,related_name='photos_reported',through='Report_Photo')
    cuisine=models.CharField(max_length=30,choices=cuisine_choices,default='none')
    pinners=models.ManyToManyField(MyUser,related_name='photos_pinned',blank=True)
    pin_points=models.IntegerField(default=0)
    points=models.IntegerField(default=0)
    user_tags = models.ManyToManyField(MyUser, related_name = 'photos_tagged_in')
    hash_tags = models.ManyToManyField(HashTag,related_name='tagged_photos')
    public=models.BooleanField(default=True)
	
    def __str__(self):
        return self.description
    
         
class Report_Photo(models.Model):
    reportedby=models.ForeignKey(MyUser,related_name='reported_photo',on_delete=models.CASCADE)
    photo=models.ForeignKey(Photo,on_delete=models.CASCADE)
    on=models.DateTimeField(auto_now_add = True)
    report_reasons = (
        ('This photo is a spam or a scam', 'This photo is spam or a scam'),
        ('This photo puts people at risk', 'This photo puts people at risk'),
        ("This photo shouldn't be on foodchaps", "This photo shouldn't be on foodchaps"),
    )
    reason=models.CharField(max_length=30,choices=report_reasons,default='none')
    def __str__(self):
        return self.reason        
   #class Meta:
        #auto_created = True
    
 
        
  
    
    

class Comment(models.Model):
    by = models.ForeignKey(MyUser)
    photo = models.ForeignKey(Photo)
    on = models.DateTimeField(auto_now_add = True)
    text = models.CharField(max_length = 100)

    def __str__(self):
        return self.text



class Recipe_Comment(models.Model):
    by = models.ForeignKey(MyUser)
    recipe = models.ForeignKey(Recipe)
    on = models.DateTimeField(auto_now_add = True)
    text = models.CharField(max_length = 100)

    def __str__(self):
        return self.text    

    



    
    
    
    
#class Pinned_Photo(models.Model):
#    by=models.ForeignKey(MyUser)
   # photo=models.ForeignKey(Photo)
  #  on=models.DateTimeField(auto_now_add = True)
 #   points=models.IntegerField(default=0)
    
#class Pinned_Recipe(models.Model):
    #by=models.ForeignKey(MyUser)
    #recipe=models.ForeignKey(Recipe)
    #on=models.DateTimeField(auto_now_add = True)    
    #points=models.IntegerField(default=0)

templates/autocomplete_postman_multiple_as1-1.html
{% extends "autocomplete.html" %}{% comment %}
This is a custom template for django-ajax-selects version 1.1.4/5 (not for 1.2+).
Channel:		postman_multiple_as1-1
Form Field:		AutoCompleteField
Usage:			Entering of multiple values.

There is no such template provided in the django-ajax-selects application.
Differences with the default template:
- it uses the "multiple: true" option of the jquery-plugin-autocomplete
- it fixes the issue http://code.google.com/p/django-ajax-selects/issues/detail?id=57
Note: this template is also used in the test suite.

{% endcomment %}
{% block script %}
	$('#{{ html_id }}').autocomplete('{{ lookup_url }}', {
		width: 320,
		formatItem: function(row) { return row[1]; },
		formatResult: function(row) { return row[2]; },
		multiple: true,
		dataType: "text"
	})
	$('#{{ html_id }}').result(function(event, data, formatted) {
		$('#{{ html_id }}').trigger("added");
	})
{% block extra_script %}{% endblock %}
{% endblock %}

templates/autocomplete_postman_multiple_as1-2.html
{% extends "autocomplete.html" %}{% comment %}
This is a custom template for django-ajax-selects version 1.2+ (not for 1.1.4/5).
Channel:		postman_multiple_as1-2
Form Field:		AutoCompleteField
Usage:			Entering of multiple values.

There is no such template provided in the django-ajax-selects application.

{% endcomment %}
{% block script %}
	addAutoComplete("{{html_id}}", function(html_id) {
		function split(val) {
			return val.split(/,\s*/);
		}
		function extractLast(term) {
			return split(term).pop();
		}

		$("#"+html_id)
		// don't navigate away from the field on tab when selecting an item
		.bind("keydown", function(event) {
			if (event.keyCode === $.ui.keyCode.TAB &&
					$(this).data("autocomplete").menu.active) {
				event.preventDefault();
			}
		})
		.autocomplete({
			source: function(request, response) {
				$.getJSON("{{lookup_url}}", {
					term: extractLast(request.term)
				}, response);
			},
			search: function() {
				// custom minLength
				var term = extractLast(this.value);
				if (term.length < {{min_length}}) {
					return false;
				}
			},
			focus: function() {
				// prevent value inserted on focus
				return false;
			},
			select: function(event, ui) {
				var terms = split(this.value);
				// remove the current input
				terms.pop();
				// add the selected item
				terms.push(ui.item.value);
				// add placeholder to get the comma-and-space at the end
				terms.push("");
				this.value = terms.join(", ");
				$(this).trigger("added");
				return false;
			}
		}).autocompletehtml();
	});
{% block extra_script %}{% endblock %}
{% endblock %}

templates/autocomplete_postman_multiple_as1-3.html
{% comment %}
This is a custom template for django-ajax-selects version 1.3+ (not for 1.2.x).
Channel:		postman_multiple_as1-3
Form Field:		AutoCompleteField
Usage:			Entering of multiple values.

There is no such template provided in the django-ajax-selects application.

This templage could almost {% extends "autocomplete.html" %}
 and our field would be first processed as an ordinary "autocomplete" by ajax_select.js.
 An autocomplete("option", opts) in the extra_script block would provide only the additions & overrides.
Alas, we need to register our keydown handler before the one set by autocomplete(),
 otherwise there will be no longer a menu.active at runtime.
So data-ajax-select has any other value - the contents doesn't matter.
{% endcomment %}
<input type="text" name="{{name}}" id="{{html_id}}" value="{{current_repr}}" autocomplete="off" data-ajax-select="autocomplete-postman" data-plugin-options="{{ data_plugin_options }}" {{ extra_attrs }} />
<script type="text/javascript">
(function ($) {
  $(document).ready(function(){
    {# can't call addAutoComplete() here, available only in the scope of ajax_select.js inner function #}
    var $inp = $("#{{html_id}}"),
      opts = JSON.parse($inp.attr('data-plugin-options'));

    {# derived from http://jqueryui.com/resources/demos/autocomplete/multiple-remote.html #}
    function split(val) {
      return val.split(/,\s*/);
    }
    function extractLast(term) {
      return split(term).pop();
    }
    $inp.bind("keydown", function(event) {
      {# don't navigate away from the field on tab when selecting an item #}
      if (event.keyCode === $.ui.keyCode.TAB &&
          $(this).data("ui-autocomplete").menu.active) {  {# autocomplete("instance") is 1.11, not 1.10 of v1.3.6 #}
        event.preventDefault();
      }
    });
    var option_source = opts.source;
    opts.source = function(request, response) {
        $.getJSON(option_source, {
          term: extractLast(request.term)
        }, response);
      };
    opts.search = function() {
        {# custom minLength #}
        var term = extractLast(this.value);
        if (term.length < {{min_length}}) {
          return false;
        }
      };
    opts.focus = function() {
        {# prevent value inserted on focus #}
        return false;
      };
    opts.select = function(event, ui) {
        var terms = split(this.value);
        {# remove the current input #}
        terms.pop();
        {# add the selected item #}
        terms.push(ui.item.value);
        {# add placeholder to get the comma-and-space at the end #}
        terms.push("");
        this.value = terms.join(", ");
        $(this).trigger("added", [ui.item.pk, ui.item]);
        return false;
      };
    $inp.autocomplete(opts);
  });
})(window.jQuery);
</script>
{% block help %}{% if help_text %}<p class="help">{{ help_text }}</p>{% endif %}{% endblock %}

templates/autocomplete_postman_single_as1-1.html
{% extends "autocomplete.html" %}{% comment %}
This is a custom template for django-ajax-selects version 1.1.4/5 (not for 1.2+).
Channel:		postman_single_as1-1
Form Field:		AutoCompleteField
Usage:			Basic entering of a single value.

It is the same as the default template, except that it fixes the issue:
http://code.google.com/p/django-ajax-selects/issues/detail?id=57
Note: this template is also used in the test suite.

{% endcomment %}
{% block script %}
	$('#{{ html_id }}').autocomplete('{{ lookup_url }}', {
		width: 320,
		formatItem: function(row) { return row[1]; },
		formatResult: function(row) { return row[2]; },
		dataType: "text"
	})
	$('#{{ html_id }}').result(function(event, data, formatted) {
		$('#{{ html_id }}').trigger("added");
	})
{% block extra_script %}{% endblock %}
{% endblock %}

templates/recipe.html
{% load static %}
	<!DOCTYPE html>
	<html>
    <head>
	 <script  src="{% static "js/jquery-2.1.3.js"%}" type="text/javascript"></script>
		<!--<script  src="{% static "js/comment.js"%}" type="text/javascript"></script>-->
		<script  src="{% static "js/bootstrap.min.js"%}" type="text/javascript"></script>

        <title> {%block title%} Welcome  {% endblock %} </title>
     <!--  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
       -->
	       <link  type="text/css" href="{% static "css/boot.css"%}" rel="stylesheet">
			 <link  href="{% static "css/home.css"%}" type="text/css"  rel="stylesheet">
			 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		  <script>
        $(document).ready(function(){
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function vote(recipeID){
$.ajax({
	type:"POST",
	url:"/deleterecipe/",
	data:{"recipe":recipeID},
	success: function(){
	$("#recipe-delete-" + recipeID).hide();
	$("#recipe-" + recipeID).hide();
	},
	headers:{
	'X-CSRFToken' :csrftoken
	}
});
return false;

}
$(".delete").click(function(){

var recipeID=parseInt(this.id.split("-")[2]);
console.log(recipeID);

return vote(recipeID);

})


function pin(recipeID){
$.ajax({
	type:"POST",
	url:"/pin_recipe/",
	data:{"recipe":recipeID},
	success: function(result){
	$("#recipe-pin-" + recipeID).hide();
        $("#pin-span-" + recipeID).hide();
        $("#pin-p-" + recipeID).prepend('<span></span>');
        $("#pin-p-" + recipeID + ">" + "span").attr('id', "pinspan" + recipeID);
        $("#pinspan" + recipeID).text(result);
        
        
        
	
    },
	headers:{
	'X-CSRFToken' :csrftoken
	}
});
return false;

}
$("button.pin").click(function(){

var recipeID=parseInt(this.id.split("-")[2]);
console.log(recipeID);

return pin(recipeID);

})



function addcomment(photoID,text){
$.ajax({
	type:"POST",
	url:"/addcommentrecipe/",
	data:{"recipe":photoID,"text":text},
	success: function(){
        console.log("hogya");
	$("#like-p-" + photoID).append('<p></P>');
        counter=Math.round(Math.random() * 323234 + 5)
    $("#like-p-" + photoID + ">" + "p").attr('id', "commentp" + counter);
        
    $("#commentp" + counter).text(text);    
        
       
	},
	headers:{
	'X-CSRFToken' :csrftoken
	}
});
return false;

}
$("a.addcomment").click(function(){
var photoID=parseInt(this.id.split("-")[2]);
console.log(photoID);
photomy=photoID+"";
    var text=$("#"+photomy).val();
    console.log(text);
return addcomment(photoID,text);

})

});
</script>
    </head>
    <body>
        <!--<input type ="text" id = "autoComplete">
        <script>
            $(document).ready(function() {
                $('#autoComplete').autocomplete({source: '/searchuser', minlength: 2});
            });
        </script>
		-->
		<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">Foodit!</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/profile">Profile</a>
                    </li>
                    <li>
                        <a href="/userphoto">Photobucket</a>
                    </li>
                    <li>
                        <a href="/home">Photopond</a>
                    </li>
                     <li>
                        <a href="/recipes">Recipes</a>
                    </li>
                     <li>
                        <a href="/friends">Connections</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        </nav>
        <br>
        <br>
	<h1>hey {{user}} !</h1>

        
        
{% for item in recipe %}

<figure class="text-overflow col-md-3" style="background:white;" id="recipe-{{item.id}}">
<a href="/deleterecipe/" id="recipe-delete-{{item.id}}" class="delete glyphicon glyphicon-remove-circle" style="margin-bottom:5px;"></a>

                                <a href="#">
                                    <img src="{{item.photo.url}}" id="photo-{{item.id}}"/>
                                </a>
    {% if user.is_authenticated and item not in user.recipe_liked.all %}

<span style="float:right;"><a href="/vote/" id="photo-vote-{{item.id}}" class="vote">vote</a></span></p>
{% endif %} 
        
        
        
        
        <ul>                                  
 {% for comments in item.recipe_comment_set.all %}
                                    
<li>{{comments}} <span> by {{comments.by}}</span></li>
                            
                                    {% endfor %}
                                    
</ul>  
<div id="commentinput" class="row">
<label for="id_text">Comment:</label> 
<input id="{{item.id}}" maxlength="100" name="text" type="text"/>
<a href="/addcommentrecipe/" id="photo-addcomment-{{item.id}}" class="addcomment">submit</a>
</div>
        
        
        
        
        
        
							
                                <figcaption>

                                        <h3><small>by {{item.by}}</small></h3>
                         <p class="top"><span>INGREDIENTS:</span><br>{{item.ingredients}}</p>
                        <p class="top"><span>METHOD:</span><br>{{item.method}}</p>
                 <p class="top"><span>PREPARATION TIME:</span>{{item.prep_time}}</p>
                <p class="top"><span>COOKING TIME:</span>{{item.Cook_time}}</p>                    


						 
                               
                                </figcaption>
        
        
        
        
        
        
                                         
                                    
	{% if item.pinners.all %}
								pinned by
								{% endif %}
{% for pinners in item.pinners.all %}
								
                               <li style="display:inline;">{{pinners}}</li>
							   
							   {% endfor %}
							   </ul>
						 <p id="pin-p-{{item.id}}"><span id="pin-span-{{item.id}}">{{item.pin_points}}</span> pins <!-- <a onclick="show()" style="cursor:pointer;">likes</a>-->                                     
									   {% if user.is_authenticated and item not in user.recipe_pinned.all %}

<span style="float:right;"><button href="/pin_recipe/" id="recipe-pin-{{item.id}}" class="pin">pin</button></span></p>
{% endif %}                                     
                                    
                                    
            
        
        
        
        
        
        
								
                            </figure>
							{% endfor %}

        
   
<div class="container">      
<form action="/addrecipe/" method="post" enctype="multipart/form-data" role="form">{% csrf_token %}
<!--<div class="form-group col-lg-6 col-lg-offset-6">
<label for="id_image">Image:</label> 
<input id="id_image" name="image" type="file" class="form-control"/>
</div>-->

<div class="row">
<div class="form-group col-lg-3">
<span class="btn btn-default btn-file">
imagefile <input type="file" id="id_photo" name="photo">
</span>
</div>
</div>
<div class="row">
<div class="form-group col-lg-9">
<label for="id_title">Title:</label> 
<textarea cols="5" id="id_description" maxlength="100" name="title" rows="3" class="form-control">
</textarea>
</div>
</div>
<div class="row">
<div class="form-group col-lg-9">
<label for="id_title">Ingredients:</label> 
<textarea cols="10" id="id_ingredients" maxlength="1000" name="ingredients" rows="5" class="form-control">
</textarea>
</div>
</div>    
<div class="row">
<div class="form-group col-lg-9">
<label for="id_title">Method:</label> 
<textarea cols="15" id="id_method" maxlength="2000" name="method" rows="10" class="form-control">
</textarea>
</div>
</div>    
<div class="row">
<div class="form-group col-lg-9">
<label for="id_prep_time">Preparation Time:</label> 
<input type="text" class="form-control" name="prep_time" id="id_prep_time" >
</div>
</div>
<div class="row">
<div class="form-group col-lg-9">
<label for="id_cook_time">Cooking Time:</label> 
<input type="text" class="form-control" name="cook_time" id="id_cook_time" >
</div>
</div>    
<div class="row">
<div class="form-group col-lg-3">
<input type="submit" value="addrecipe" name="addrecipe" class="form-control" id="addone"/>
</div>
</div>
</form>
</div>          
                

</body>
</html>